### ISSUE TITLE
error compiling camfort

### ISSUE THREAD

**Issue by wadudmiah** [dorchard/camfort#7]
Hello, 

I am getting the following error when trying to built camfort on Fedora 21:

[miahw@bengal camfort]$ ghci Main.hs
GHCi, version 7.6.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
[ 4 of 19] Compiling Analysis.Annotations ( Analysis/Annotations.hs, interpreted )

Analysis/Annotations.hs:42:47:
    Not in scope: type constructor or class `SrcLoc'
Failed, modules loaded: Extensions.UnitsEnvironment, Extensions.UnitsSolve, Analysis.IntermediateReps.
Prelude Extensions.UnitsSolve> 

Any help will be greatly appreciated.

**Comment by acr31** [comment]
Hi,

Do you have the most recent version of language-fortran installed?   You should compile this from source and install it.  Here is the repo: https://github.com/dagit/language-fortran

Yours,

Andy

**Comment by wadudmiah** [comment]
hi, thanks for the quick reply. The version I have installed is:
[miahw@bengal camfort]$ cabal info language-fortran
* language-fortran (library)
    Synopsis:      Fortran lexer and parser, language support, and extensions.
    Versions available: 0.2.7
    Versions installed: 0.2.7

The version from Git is 0.2.0 which failed to install:

[miahw@bengal camfort]$ cabal install language-fortran/language-fortran.cabal 
Resolving dependencies...
Configuring language-fortran-0.2.0.0...
Building language-fortran-0.2.0.0...
Preprocessing library language-fortran-0.2.0.0...
unused rules: 12
unused terminals: 8
shift/reduce conflicts:  30
cabal: can't find source for Language/Fortran/Pretty in src,
dist/build/autogen
Failed to install language-fortran-0.2.0.0
cabal: Error: some packages failed to install:
language-fortran-0.2.0.0 failed during the building phase. The exception was:
ExitFailure 1
[miahw@bengal camfort]$ 

Is this how you install it? I am not familiar with Haskell at all.

**Comment by dorchard** [comment]
Hi! Sorry for this. The actual version of language-fortran we are using is here:
https://github.com/dorchard/language-fortran

I have just pushed a new version to Haskell's package manager:
http://hackage.haskell.org/package/language-fortran-0.3
But it might not be indexed by Cabal for another day. So you are better of probably cloning from here: 
https://github.com/dorchard/language-fortran

Then doing: 
cabal configure
cabal build
cabal install

Thanks for your help/patience :)

**Comment by wadudmiah** [comment]
Hi dorchard,

Thanks for that! I've managed to get camfort built for Fedora 21. There were many missing steps, but I've got it to work now. Now it's time for me to use it for my Fortran codes!

Cheers again. You can close this ticket now.

**Comment by dorchard** [comment]
Thanks! No problem.
Please let us know if you encounter any problems. CamFort is very much in development, and we would greatly appreciate any feedback so we can improve things. 
Btw, I just pushed a change which improves the command line interface (makes it easier to use) so you might want to update. 

Best,
Dominic
