### ISSUE TITLE
Continuation lines in arguments throw the parser off

### ISSUE THREAD

**Issue by kokes** [dorchard/camfort#9]
When I have subroutine arguments over more than one line, `commonArg` stops working properly.

An example:
```
subroutine test(a, b, &
				c)

integer :: c1, c2, c3
COMMON /foo/  c1, c2, c3

real :: a, b, c

print *, a, b, c

end subroutine test
```

would result in

```
subroutine test(a, b, &
				c),c1,c2,c3

integer :: c1, c2, c3


real :: a, b, c

print *, a, b, c

end subroutine test
```

I'm using the master, compiled just moments ago.

**Comment by madgen** [comment]
@dorchard I have checked if this is a language-fortran parser problem. It doesn't seem like it as other analyses works fine.

**Comment by dorchard** [comment]
Thanks. I'm almost certain this is a bug in the refactoring case for function arguments.

**Comment by madgen** [comment]
I can confirm this patch fixes the issue (at least for this example).

@kokes thank you for reporting this. Please let us know if you encounter other bugs. I'll reopen the issue if it is needed.
